// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXH9hHr8gXEWHhOib2jbpuETs9lI0OA30',
    appId: '1:619357209415:web:a343807e7a1274ca160262',
    messagingSenderId: '619357209415',
    projectId: 'coop-farm-flutter',
    authDomain: 'coop-farm-flutter.firebaseapp.com',
    databaseURL: 'https://coop-farm-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'coop-farm-flutter.firebasestorage.app',
    measurementId: 'G-KW6HFBRGBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjDclCUHYm0k9XlXK5OzN2OwLSFTH-zzo',
    appId: '1:619357209415:android:687d1712078b268a160262',
    messagingSenderId: '619357209415',
    projectId: 'coop-farm-flutter',
    databaseURL: 'https://coop-farm-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'coop-farm-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL_6n1pOjjET5vZ28XIZIOAnB0XiGn4yg',
    appId: '1:619357209415:ios:e613964d367d71c7160262',
    messagingSenderId: '619357209415',
    projectId: 'coop-farm-flutter',
    databaseURL: 'https://coop-farm-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'coop-farm-flutter.firebasestorage.app',
    iosBundleId: 'com.example.coopFarmFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL_6n1pOjjET5vZ28XIZIOAnB0XiGn4yg',
    appId: '1:619357209415:ios:e613964d367d71c7160262',
    messagingSenderId: '619357209415',
    projectId: 'coop-farm-flutter',
    databaseURL: 'https://coop-farm-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'coop-farm-flutter.firebasestorage.app',
    iosBundleId: 'com.example.coopFarmFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXH9hHr8gXEWHhOib2jbpuETs9lI0OA30',
    appId: '1:619357209415:web:3b09ded59a71b3db160262',
    messagingSenderId: '619357209415',
    projectId: 'coop-farm-flutter',
    authDomain: 'coop-farm-flutter.firebaseapp.com',
    databaseURL: 'https://coop-farm-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'coop-farm-flutter.firebasestorage.app',
    measurementId: 'G-SZTMGRXS2R',
  );
}
